title: 「リカル オキン」
description: Official website and documentation for the UTAU voicebank Rikaru Okin.
theme: jekyll-theme-primer # A fallback default
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
